### ISSUE TITLE
IndexOutOfRangeException when executing the status command.

### ISSUE THREAD

**Issue by tusmester** [kavics/GitTools#25]
This is what I got when I tried to execute the `status` command.

```
d:\Dev\github>gitt.exe status
REPOSITORIES
Repository                              Current branch                Status                   Modified/Last Fetch
======================================= ============================= ======================== ===================
GitTools                                develop                                                6 minutes ago
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GitT.Commands.StatusCommand.ParseStatus(RepositoryInfo repo, String gitOut) in D:\Dev\github\GitTools\src\GitT\Commands\StatusCommand.cs:line 101
   at GitT.Commands.StatusCommand.<>c__DisplayClass17_0.<CurrentBranch2>b__0(String r) in D:\Dev\github\GitTools\src\GitT\Commands\StatusCommand.cs:line 80
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at GitT.Commands.StatusCommand.CurrentBranch2(String path, Boolean fetch) in D:\Dev\github\GitTools\src\GitT\Commands\StatusCommand.cs:line 85
   at GitT.Commands.StatusCommand.Execute() in D:\Dev\github\GitTools\src\GitT\Commands\StatusCommand.cs:line 34
   at GitT.Program.Run(String githubContainer, String[] args) in D:\Dev\github\GitTools\src\GitT\Program.cs:line 53
```

#### Possible causes

- the `GitTools` repo is readonly to me
- the _next_ folder (not in the log above) is not a repository, just a random folder

**Comment by kavics** [comment]
This bug has been fixed in the latest release,
